### ISSUE TITLE
Consider removing the dependency on fmt for usage in wasm

### ISSUE THREAD

**Issue by advdv** [lithdew/casso#1]
Hey, thank you for taking the time to build this library! I haven't had time to use it myself but one of the usecases that strikes me is the creation of WASM applications in the browser. For that scenario it would be really usefull if the usage of fmt is minimized because it increases the file size of the wasm binary so much. 

This might not be the usecase you had in mind yourself but since fmt is just used to create an error in this library it might be an easy fix.

Let me know what you think!

**Comment by lithdew** [comment]
I pushed a commit to remove `fmt` from being referenced in the source files for this package, though I am not 100% sure if this is enough to stop `fmt` from being referenced in this library at all.

Let me know if my commit fixes it, otherwise happy to further investigate this! Thank you :smile:.

**Comment by advdv** [comment]
That is great! thank you
